In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [4]:
x = np.array(my_list)

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
list(range(0,5))

[0, 1, 2, 3, 4]

In [10]:
np.arange(0,5)
# numpy version of range

array([0, 1, 2, 3, 4])

In [11]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [13]:
np.zeros((4,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [16]:
np.ones((3,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [18]:
# Evenly spaced numbers over a range
np.linspace(0,10,3)

array([  0.,   5.,  10.])

In [19]:
# Identity matrix... Diagonal is one
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [22]:
# Random numbers between 0 and 1 from a uniform distribution
np.random.rand(5,5)

array([[ 0.43718659,  0.67749606,  0.73564352,  0.82199412,  0.29971069],
       [ 0.62814118,  0.04659492,  0.96611956,  0.64034435,  0.60714315],
       [ 0.77662695,  0.87019591,  0.2750405 ,  0.34978317,  0.92604543],
       [ 0.68913525,  0.31628208,  0.61291416,  0.34264602,  0.41827022],
       [ 0.14566542,  0.41232438,  0.79820307,  0.5294253 ,  0.08112119]])

In [23]:
# Standard normal distribution... Centered at 0.
np.random.randn(5,4)

array([[ 1.64052675,  0.58932311,  1.14136857, -0.91953421],
       [ 0.59698051, -0.69413421,  0.86137403,  0.55488602],
       [-1.207793  ,  0.53674496,  0.69884802,  0.09818436],
       [-1.16837402,  0.15202322, -0.85845225, -0.86304721],
       [-0.13009494, -1.42757722,  0.0464376 , -0.17529177]])

In [30]:
# Random integer between the two arguments
np.random.randint(0,10)

5

In [31]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [33]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [34]:
arr.shape

(25,)

In [35]:
arr.reshape(5,5).shape

(5, 5)

In [36]:
arr.dtype

dtype('int32')

In [37]:
ranarr

array([44,  9, 26, 28, 27,  8, 14, 27, 10,  9])

In [38]:
ranarr.max()

44

In [39]:
# Index location of maximum value
ranarr.argmax()

0

In [40]:
ranarr.min()

8

In [41]:
ranarr.argmin()

5

Numpy Operations

In [44]:
arr = np.arange(0,10)

In [46]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [48]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [49]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [50]:
arr/arr

C:\Users\student\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ nan,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.])

In [51]:
arr ** 3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [52]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [53]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [54]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [55]:
np.max(arr)

9

In [56]:
arr.max()

9

In [57]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [58]:
np.log(arr)

C:\Users\student\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436,
        1.60943791,  1.79175947,  1.94591015,  2.07944154,  2.19722458])

Numpy Indexing and Selection

In [59]:
arr = np.arange(0,11)

In [60]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
arr[8]

8

In [62]:
arr[1:5]

array([1, 2, 3, 4])

In [63]:
arr[:5]

array([0, 1, 2, 3, 4])

In [64]:
arr[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

Broadcasting

In [65]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

^ Can't do that with a normal Python list

In [67]:
arr = np.arange(0,11)

In [68]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
slice_of_arr = arr[0:6]

In [70]:
slice_of_arr[:] = 99

In [71]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

^ Note how this changes everything, like a pointer. 
If you want to copy, you need to actually call .copy()

In [72]:
arr_copy = arr.copy()

In [73]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [74]:
arr_copy[:] = 200

In [75]:
arr_copy

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200])

In [76]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [78]:
mat = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [79]:
mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [81]:
# First Row
mat[0]

array([ 5, 10, 15])

In [83]:
mat[1][1]

25

In [84]:
mat[1,1]

25

In [86]:
mat[0:2,1:]

array([[10, 15],
       [25, 30]])

In [88]:
mat[1:,:2]

array([[20, 25],
       [35, 40]])

Conditional Selection

In [89]:
arr = np.arange(1,11)

In [90]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [91]:
arr >  4

array([False, False, False, False,  True,  True,  True,  True,  True,  True], dtype=bool)

In [92]:
bool_arr = arr > 4

In [94]:
# Only returns the array where these booleans are True.
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [96]:
# Same Result
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [97]:
arr[arr <= 9]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])